/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface AgappeComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface AgappeComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AgappeComponent': Components.AgappeComponent;
  }

  interface StencilIntrinsicElements {
    'agappe-component': Components.AgappeComponentAttributes;
  }


  interface HTMLAgappeComponentElement extends Components.AgappeComponent, HTMLStencilElement {}
  var HTMLAgappeComponentElement: {
    prototype: HTMLAgappeComponentElement;
    new (): HTMLAgappeComponentElement;
  };

  interface HTMLElementTagNameMap {
    'agappe-component': HTMLAgappeComponentElement
  }

  interface ElementTagNameMap {
    'agappe-component': HTMLAgappeComponentElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
